import { getLocale, getTranslations } from "next-intl/server";
import Image from "next/image";
import { assets } from "@/core/data/assets";
import { Container, Section } from "@/presentation/components/ui/Layout";
export type CaseStudy = { name: string; client: string; need: string; solution: string; result?: string; role: string; status: string; tags: string[] };
export function ProjectVisual({ images, title }: { images: (string | null)[]; title: string }) {
 const supplied = images.filter((src): src is string => Boolean(src));
 if (!supplied.length) return null;
 return <div className={`project-assembly ${supplied.length > 1 ? "is-stacked" : ""}`}><svg aria-hidden="true" viewBox="0 0 600 380" className="assembly-lines"><path d="M20 300H140V50H560M60 340H500V100H580" fill="none" stroke="currentColor"/><circle cx="140" cy="300" r="50" fill="none" stroke="currentColor"/></svg>{supplied.map((src,index)=><div key={src} className={`assembly-screen screen-${index}`}><Image src={src} alt={`${title}${supplied.length>1?` — ${index===0?'Cahier Boulanger':'Cahier Opticien'}`:''}`} width={1910} height={915} sizes="(max-width: 1024px) 90vw, 600px" className="h-auto w-full"/></div>)}</div>;
}
export function CaseDetails({project,labels}:{project:CaseStudy;labels:{need:string;solution:string;result:string;role:string}}){return <><dl className="mt-6 space-y-4 text-sm leading-6">{(["need","solution","result","role"] as const).filter(key => key !== "result" || Boolean(project.result)).map(key=><div key={key}><dt className="font-mono text-xs font-semibold">{labels[key]}</dt><dd className="mt-1 text-muted">{project[key]}</dd></div>)}</dl><ul aria-label="Stack" className="mt-6 flex flex-wrap gap-2">{project.tags.map(tag=><li key={tag} className="tag border border-card-border px-2 py-1 text-[11px]">{tag}</li>)}</ul></>;}
export async function SelectedWork(){
 const t=await getTranslations('SelectedWork'),p=await getTranslations('Projects.page'),locale=await getLocale();const projects=t.raw('items') as CaseStudy[];
 return <Section id="projects" className="py-20 md:py-28"><Container><p className="section-label text-xs uppercase tracking-widest">{t('title')}</p><h2 className="mt-3 text-4xl font-semibold">{t('title')}</h2><div className="mt-12 space-y-16">{projects.map((project,index)=><article key={project.name} className="selected-project"><div className="relative z-10 p-6 md:p-10"><p className="section-label text-xs uppercase tracking-widest text-muted">{project.client}</p><h3 className="mt-3 text-3xl font-semibold">{project.name}</h3>{index === 1 && <p className="mt-2 font-mono text-xs">{project.status}</p>}<CaseDetails project={project} labels={{need:p('need'),solution:p('solution'),result:p('result'),role:p('role')}}/><a className="project-link mt-7 inline-flex border-b border-current pb-2 text-sm font-semibold" href={index===0?'https://ciforms-web.woez-app.com/':`/${locale}/projects`}>{index===0?t('viewProject'):t('viewAll')} <span aria-hidden="true" className="ml-3">↗</span></a></div><ProjectVisual title={project.name} images={index===0?[assets.CIFORMS_SCREENSHOT]:[assets.CAHIER_SCREENSHOT_BOULANGER,assets.CAHIER_SCREENSHOT_OPTICIEN]}/></article>)}</div></Container></Section>;
}
export async function About(){const t=await getTranslations('About');return <Section id="about" className="py-20 md:py-28"><Container><div className="grid gap-8 border-t border-card-border pt-10 md:grid-cols-[1fr_2fr]"><h2 className="text-4xl font-semibold">{t('title')}</h2><p className="max-w-3xl text-lg leading-9 text-muted">{t('text')}</p></div></Container></Section>;}
export async function Training(){const t=await getTranslations('Training');const education=t.raw('educationItems') as string[],sharing=t.raw('sharingItems') as {text:string;status:string}[];return <Section id="training" className="py-20 md:py-28"><Container><h2 className="text-4xl font-semibold">{t('title')}</h2><div className="training-assembly mt-12"><div className="training-panel"><h3 className="text-2xl font-semibold">{t('education')}</h3><ul className="mt-6 divide-y divide-card-border">{education.map(item=><li key={item} className="py-4 text-sm leading-6">{item}</li>)}</ul></div><div className="training-panel sharing-panel"><h3 className="text-2xl font-semibold">{t('sharing')}</h3><ul className="mt-6 space-y-6">{sharing.map(item=><li key={item.text} className="text-sm leading-6"><p>{item.text}</p>{item.status&&<strong className="mt-2 inline-block border-l-2 border-[var(--accent)] pl-3 font-mono text-xs">{item.status}</strong>}</li>)}</ul>{assets.TRAINING_IMAGE&&<Image src={assets.TRAINING_IMAGE} alt={t('imageAlt')} width={700} height={500} sizes="(max-width: 768px) 90vw, 500px" className="mt-8 h-auto w-full"/>}</div></div></Container></Section>;}
